name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  msgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.2.2
      - uses: actions/checkout@v2.3.5
      - run: sudo apt install -y gettext aspell libenchant-dev
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('lint-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install -r lint-requirements.txt
      - run: msgcheck -n stdimage/locale/*/LC_MESSAGES/*.po

  lint:
    strategy:
      fail-fast: false
      matrix:
        lint-command:
          - "bandit -r . -x ./tests"
          - "black --check --diff ."
          - "flake8 ."
          - "isort --check-only --diff ."
          - "pydocstyle ."
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.2.2
      - uses: actions/checkout@v2.3.5
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('lint-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install -r lint-requirements.txt
      - run: ${{ matrix.lint-command }}


  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Install gettext
        run: sudo apt install gettext -y
      - uses: actions/setup-python@v2.2.2
      - run: python -m pip install --upgrade pip setuptools wheel twine readme-renderer
      - uses: actions/checkout@v2.3.5
      - run: python setup.py sdist bdist_wheel
      - run: python -m twine check dist/*
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  pytest:
    runs-on: ubuntu-latest
    needs:
      - lint
      - msgcheck
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
        django-version:
          - "2.2.*"
          - "3.1.*"
          - "3.2.*"
        extra:
          - ""
          - "progressbar"
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
    - run: sudo apt install gettext -y
    - uses: actions/checkout@v2.3.5
    - run: python -m pip install --upgrade pip setuptools codecov wheel
    - run: python -m pip install .[${{ matrix.extra }}]
      if: ${{ matrix.extra }}
    - run: python -m pip install django==${{ matrix.django-version }}
    - name: Test with pytest
      run: python setup.py test
    - run: codecov
